### ISSUE TITLE
A problem for deploy

### ISSUE THREAD

**Issue by always-waiting** [sameersbn/docker-gitlab-ci-multi-runner#30]
This is my .gitlab-ci.yml
```
stages:
  - build
  - test
  - deploy

python-build:
  stage: build
  tags:
    - ubuntu16.04
    - build
    - python
  environment: build-stage
  before_script:
    - pwd
    - ls -al ./
  script:
    - python setup.py sdist
    - ls -al ./
  artifacts:
    name: "test-mxc"
    paths:
    - bin
    expire_in: 1 week

python-test:
  stage: test
  tags:
    - ubuntu16.04
    - python
    - test
  before_script:
    - pwd
    - ls -al ./
  script:
    - python setup.py test

python-deploy:
  stage: deploy
  tags:
    - deploy
    - python
  allow_failure: true
  before_script:
    - hostname
    - whoami
  script:
    - pwd
    - ls .
  after_script:
    - rm -rf ~/builds
```

When gitlab-ci runs in deploy stage, there is a error which i don't know why

```
Running with gitlab-ci-multi-runner 1.6.1 (c52ad4f)
Using SSH executor...
Running on berry_testserver via 7ab9ea84591a...
Fetching changes...
HEAD is now at 99d4359 Add before_script
From http://192.168.4.6:10080/bixichao/python-mxcfun
 + 99d4359...5641972 master     -> origin/master  (forced update)
Checking out 56419722 as master...
Downloading artifacts for python-build (61)...
Downloading artifacts from coordinator... ok        id=61 responseStatus=200 OK token=9uZ8mCME
FATAL: zip: not a valid zip file                   
ERROR: Build failed: Process exited with: 1. Reason was:  ()
```
