### ISSUE TITLE
How can I interconnect this with gitlab in docker on the same host?

### ISSUE THREAD

**Issue by pmalek** [sameersbn/docker-gitlab-ci-multi-runner#4]
I have ran you [gitlab in docker](https://github.com/sameersbn/docker-gitlab) and I would like to connect multi-runner to it but I am getting

```
Starting dockergitlabcimultirunner_GitlabCIMultiRunner_1...
Attaching to dockergitlabcimultirunner_GitlabCIMultiRunner_1
GitlabCIMultiRunner_1 | time="2015-09-25T18:41:11Z" level=error msg="Couldn't execute POST against 172.17.42.1/api/v1/runners/register.json: Post 172.17.42.1/api/v1/runners/register.json: unsupported protocol scheme \"\"" 
GitlabCIMultiRunner_1 | time="2015-09-25T18:41:11Z" level=error msg="79e66ea0 Registering runner... failed" 
GitlabCIMultiRunner_1 | time="2015-09-25T18:41:11Z" level=fatal msg="Failed to register this runner. Perhaps you are having network problems" 
.....
```

I have added `external_link` in the `docker-compose.yml`

```
GitlabCIMultiRunner:
  image: sameersbn/gitlab-ci-multi-runner:0.5.5
  external_links:
    - dockergitlab_gitlab_1
  volumes:
    - /opt/gitlab-ci-multi-runner:/home/gitlab_ci_multi_runner/data
  environment:
    - CI_SERVER_URL=172.17.42.1
    - RUNNER_TOKEN=79e66ea069a011eae67c
    - RUNNER_DESCRIPTION=first_runner
    - RUNNER_EXECUTOR=shell
  restart: always
```

Am I doing this in correct way? The IP address I have put there is the `ifconfig docker0` from gitlab instance. I have tried with:
* 172.17.42.1
* 172.17.42.1:10800
* localhost
* localhost:10800

with the same results

Gitlab containers are running as follows:

```
CONTAINER ID        IMAGE                        COMMAND                CREATED             STATUS              PORTS                                                                  NAMES
37d346a08f67        sameersbn/gitlab:8.0.2       "/sbin/entrypoint.sh   About an hour ago   Up About an hour    0.0.0.0:10022->22/tcp, 0.0.0.0:10080->80/tcp, 0.0.0.0:32788->443/tcp   dockergitlab_gitlab_1       
e2f3dba05391        sameersbn/redis:latest       "/sbin/entrypoint.sh   21 hours ago        Up About an hour    0.0.0.0:32787->6379/tcp                                                dockergitlab_redis_1        
afd6764750d7        sameersbn/postgresql:9.4-3   "/start"               21 hours ago        Up About an hour    0.0.0.0:32786->5432/tcp                                                dockergitlab_postgresql_1 
```

**Comment by tamlyn** [comment]
You want to use the full URL including scheme, port and path. So in your case probably `http://172.17.42.1:10800`. (Are you sure it's not `10080`?) Note if you're using Gitlab CE 8 which has Gitlab CI integrated, you need to add `/ci/` to the end of the URL so `http://172.17.42.1:10800/ci/`

**Comment by pmalek** [comment]
OK I have managed to get it to work by running the following command to get the IP address of gitlab containter:

```
$ sudo docker exec -it dockergitlab_gitlab_1 ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
196: eth0@if197: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:32 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.50/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:32/64 scope link 
       valid_lft forever preferred_lft forever
```

and then I have used the following setting:

```
CI_SERVER_URL=http://172.17.0.50/ci
```

with this it works :) Although I wonder why is my `ifconfig docker0` IP address different than the one returned from `docker exec -it dockergitlab_gitlab_1 ip addr` ?

**Comment by sameersbn** [comment]
Of your docker compose has the config:

```yaml
ports:
    - "10080:80"
```

or if your docker run command has `-p 10080:80`, then you are better off using http://172.17.41.1:10080/ci as the url in your runner configurations. This is because when your host or container is restarted, it will not have the same ip address that it currently has. As a result the runner will no longer be able to connect to Gitlab.

**Comment by pmalek** [comment]
Ok so I needed to add `http://` in the beginning of the URL and add `/ci` postfix and it works :)

@sameersbn Thanks for pointing this out :)

**Comment by pmalek** [comment]
Weird things started to happen... I am trying to start multi-runner now and I get this:

```
sudo docker-compose up
Starting dockergitlabcimultirunner_GitlabCIMultiRunner_1...
Attaching to dockergitlabcimultirunner_GitlabCIMultiRunner_1
GitlabCIMultiRunner_1 | time="2015-09-26T12:27:37Z" level=info msg="0 Starting multi-runner from /home/gitlab_ci_multi_runner/data/config.toml ..." 
GitlabCIMultiRunner_1 | time="2015-09-26T12:27:40Z" level=error msg="Couldn't execute POST against http://172.17.0.50/ci/api/v1/builds/register.json: Post http://172.17.0.50/ci/api/v1/builds/register.json: dial tcp 172.17.0.50:80: no route to host" 
GitlabCIMultiRunner_1 | time="2015-09-26T12:27:40Z" level=warning msg="3863bfa5 Checking for builds... failed" 
```

I have no idea where `172.17.0.50` is taken from since I have the following `docker-compose.yml` (which was working few hours ago...):

```
cat docker-compose.yml
GitlabCIMultiRunner:
  image: sameersbn/gitlab-ci-multi-runner:0.5.5
  external_links:
    - dockergitlab_gitlab_1
    - dockergitlab_redis_1
    - dockergitlab_postgresql_1
  volumes:
    - /opt/gitlab-ci-multi-runner:/home/gitlab_ci_multi_runner/data
  environment:
    - CI_SERVER_URL=http://172.17.42.1:10080/ci
    - RUNNER_TOKEN=bda1e3b735dbfb0cae50
    - RUNNER_DESCRIPTION=first_runner2
    - RUNNER_EXECUTOR=shell
  restart: always

```
